from django.db import models

# Create your models here.

class Questions(models.Model):
    num = models.IntegerField()
    ques = models.CharField(max_length=150, null=True)
    opt1 = models.CharField(max_length=150, null=True)
    opt2 = models.CharField(max_length=150, null=True)
    opt3 = models.CharField(max_length=150, null=True)
class saveProgress(models.Model):
    user = models.CharField(max_length=140, null=True)
    q1 = models.CharField(max_length=140, null=True)
    q2 = models.CharField(max_length=140, null=True)
    q3 = models.CharField(max_length=140, null=True)
    q4 = models.CharField(max_length=140, null=True)
    q5 = models.CharField(max_length=140, null=True)
    q6 = models.CharField(max_length=140, null=True)
    q7 = models.CharField(max_length=140, null=True)
    q8 = models.CharField(max_length=140, null=True)
    q9 = models.CharField(max_length=140, null=True)
    q10 = models.CharField(max_length=140, null=True)
    q11 = models.CharField(max_length=140, null=True)
    q12 = models.CharField(max_length=140, null=True)
    q13 = models.CharField(max_length=140, null=True)
    q14 = models.CharField(max_length=140, null=True)
    q15 = models.CharField(max_length=140, null=True)
    q16 = models.CharField(max_length=140, null=True)
    q17 = models.CharField(max_length=140, null=True)
    q18 = models.CharField(max_length=140, null=True)
    q19 = models.CharField(max_length=140, null=True)
    q20 = models.CharField(max_length=140, null=True)
    q21 = models.CharField(max_length=140, null=True)
    q22 = models.CharField(max_length=140, null=True)
    q23 = models.CharField(max_length=140, null=True)
    q24 = models.CharField(max_length=140, null=True)
    q25 = models.CharField(max_length=140, null=True)
    q26 = models.CharField(max_length=140, null=True)
    q27 = models.CharField(max_length=140, null=True)
    q28 = models.CharField(max_length=140, null=True)
    q29 = models.CharField(max_length=140, null=True)
    q30 = models.CharField(max_length=140, null=True)
    q31 = models.CharField(max_length=140, null=True)
    q32 = models.CharField(max_length=140, null=True)
    q33 = models.CharField(max_length=140, null=True)
    q34 = models.CharField(max_length=140, null=True)
    q35 = models.CharField(max_length=140, null=True)
    q36 = models.CharField(max_length=140, null=True)
    q37 = models.CharField(max_length=140, null=True)
    q38 = models.CharField(max_length=140, null=True)
    q39 = models.CharField(max_length=140, null=True)
    q40 = models.CharField(max_length=140, null=True)
    q41 = models.CharField(max_length=140, null=True)
    q42 = models.CharField(max_length=140, null=True)
    q43 = models.CharField(max_length=140, null=True)
    q44 = models.CharField(max_length=140, null=True)
    q45 = models.CharField(max_length=140, null=True)
    q46 = models.CharField(max_length=140, null=True)
    q47 = models.CharField(max_length=140, null=True)
    q48 = models.CharField(max_length=140, null=True)
    q49 = models.CharField(max_length=140, null=True)
    q50 = models.CharField(max_length=140, null=True)
    q51 = models.CharField(max_length=140, null=True)
    q52 = models.CharField(max_length=140, null=True)
    q53 = models.CharField(max_length=140, null=True)
    q54 = models.CharField(max_length=140, null=True)
    q55 = models.CharField(max_length=140, null=True)
    q56 = models.CharField(max_length=140, null=True)
    q57 = models.CharField(max_length=140, null=True)
    q58 = models.CharField(max_length=140, null=True)
    q59 = models.CharField(max_length=140, null=True)
    q60 = models.CharField(max_length=140, null=True)
    