# Generated by Django 4.1.5 on 2023-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='opt1',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='opt2',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='opt3',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
