# Generated by Django 4.1.7 on 2023-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mbti", "0002_questions_num_questions_opt1_questions_opt2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="opt1",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="questions",
            name="opt2",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="questions",
            name="opt3",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="questions",
            name="ques",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
