# Generated by Django 4.1.7 on 2023-03-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mbti", "0003_alter_questions_opt1_alter_questions_opt2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="saveProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=140, null=True)),
                ("q1", models.CharField(max_length=140, null=True)),
                ("q2", models.CharField(max_length=140, null=True)),
                ("q3", models.CharField(max_length=140, null=True)),
                ("q4", models.CharField(max_length=140, null=True)),
                ("q5", models.CharField(max_length=140, null=True)),
                ("q6", models.CharField(max_length=140, null=True)),
                ("q7", models.CharField(max_length=140, null=True)),
                ("q8", models.CharField(max_length=140, null=True)),
                ("q9", models.CharField(max_length=140, null=True)),
                ("q10", models.CharField(max_length=140, null=True)),
                ("q11", models.CharField(max_length=140, null=True)),
            ],
        ),
    ]
