# Generated by Django 4.1.7 on 2023-03-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mbti", "0004_saveprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveprogress",
            name="q12",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q13",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q14",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q15",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q16",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q17",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q18",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q19",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q20",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q21",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q22",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q23",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q24",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q25",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q26",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q27",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q28",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q29",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q30",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q31",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q32",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q33",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q34",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q35",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q36",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q37",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q38",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q39",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q40",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q41",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q42",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q43",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q44",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q45",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q46",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q47",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q48",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q49",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q50",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q51",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q52",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q53",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q54",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q55",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q56",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q57",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q58",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q59",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="saveprogress",
            name="q60",
            field=models.CharField(max_length=140, null=True),
        ),
    ]
