# Generated by Django 4.1.7 on 2023-03-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mbti", "0005_saveprogress_q12_saveprogress_q13_saveprogress_q14_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveprogress",
            name="mtype",
            field=models.CharField(max_length=140, null=True),
        ),
    ]
